/** Prohlášení o přístupnosti (text pro `LegalPage`, podmnožina Markdownu z `@/blog/markdown`). */
export const accessibility = {
  cs: `Verze 1.0, vydáno 5. 10. 2026.

Služba se-vezmou.cz se zavazuje zpřístupnit své webové stránky v maximální možné míře všem uživatelům.

Služba je provozována mikropodnikem (fyzickou osobou podnikající s méně než 10 zaměstnanci), a proto nespadá pod povinnosti zákona č. 424/2023 Sb., o požadavcích na přístupnost výrobků a služeb. Záleží nám ale na tom, aby svatební weby i naše rozhraní mohl používat opravdu každý, a proto toto prohlášení vydáváme dobrovolně.

## Stav souladu

Naším cílem je splňovat požadavky mezinárodního standardu WCAG 2.2 na úrovni AA. Týká se to úvodního webu, průvodce tvorbou webu, správy webu i všech šablon svatebních webů.

## Jak přístupnost testujeme

- **Automatické testy:** nástroj axe v rámci našeho CI na všech šablonách a paletách v mobilním i desktopovém zobrazení. Barevné palety se strojově kontrolují na dostatečný kontrast.
- **Ruční testy rozhraní:** kontrolujeme ovládání pouze klávesnicí, viditelnost zaměření, dotykové cíle o velikosti nejméně 44 px a chování při zvětšení textu na 400 % bez vodorovného posouvání na šířce 320 px.
- **Respektování nastavení:** aplikace reaguje na systémové omezení animací (prefers-reduced-motion).

## Známá omezení

1. **PDF ke stažení:** tiskoviny generované službou (jmenovky, svatební oznámení) nejsou tagované pro čtečky obrazovky. Všechny informace z nich jsou ale přístupné přímo na webové stránce.
2. **Mapy:** zobrazené mapy tvoří obrázkové dlaždice. Adresa místa je ale vždy k dispozici jako text spolu s odkazy do externích navigací (Google Maps, Mapy.cz).
3. **Obsah vkládaný uživateli:** snoubenci si na web vkládají vlastní texty, odkazy (například na fotogalerie) a fotografie. Rozhraní je vede k vyplnění alternativních textů u obrázků, přístupnost vloženého obsahu ani externích webů, na které odkážou, ale nemůžeme zaručit.

## Zpětná vazba a kontakt

Pokud na našem webu nebo na svatebním webu vytvořeném přes naši službu narazíte na problém s přístupností, napište nám na info@se-vezmou.cz. Odpovíme nejpozději do 5 pracovních dnů.`,
  en: `Version 1.0, published 5 October 2026.

se-vezmou.cz is committed to making its website accessible to the widest possible audience.

The service is operated by a micro-enterprise (a sole trader with fewer than 10 employees) and is therefore exempt from the obligations of the Czech Act No. 424/2023 Coll. on accessibility requirements for products and services. We still care that everyone can use our wedding websites and interfaces, which is why we publish this statement voluntarily.

## Compliance status

Our goal is to meet the international WCAG 2.2 standard at level AA. This applies to our main website, the website builder, the dashboard and all wedding website templates.

## How we test accessibility

- **Automated tests:** the axe engine in our CI pipeline across all templates and colour palettes, on mobile and desktop. Colour palettes are machine-checked for contrast.
- **Manual interface tests:** we verify keyboard-only operation, visible focus, touch targets of at least 44 px, and behaviour at 400% text zoom without horizontal scrolling at 320 px width.
- **User preferences:** the application respects the system-level reduced-motion setting (prefers-reduced-motion).

## Known limitations

1. **Downloadable PDFs:** print materials generated by the service (name tags, invitations) are not tagged for screen readers. All information in them is available as text on the website itself.
2. **Maps:** embedded maps are image tiles. The venue address is always available as text, together with links to external navigation apps (Google Maps, Mapy.cz).
3. **User-generated content:** couples add their own texts, links (for example to photo galleries) and photos. The interface encourages them to provide alternative text for images, but we cannot guarantee the accessibility of the content they add or of the third-party websites they link to.

## Feedback and contact

If you encounter an accessibility barrier on our main site or on a wedding website created with our service, write to us at info@se-vezmou.cz. We aim to reply within 5 business days.`,
};
