/** Prohlášení o přístupnosti: znění v2 (text přesně podle revidovaného dokumentu), pro `LegalPage`; podmnožina Markdownu z `@/blog/markdown`. */
export const accessibility = {
  cs: `Služba **se-vezmou.cz** se snaží zpřístupňovat své webové stránky a uživatelské rozhraní co nejširšímu okruhu uživatelů, včetně osob se zdravotním postižením nebo jiným omezením.

Provozovatel služby je v současnosti mikropodnikem ve smyslu zákona č. 424/2023 Sb., o požadavcích na přístupnost některých výrobků a služeb. Na služby poskytované mikropodnikem se povinnosti tohoto zákona nevztahují. Toto prohlášení proto vydáváme dobrovolně jako vyjádření našeho přístupu k přístupnosti.

## Stav přístupnosti

Naším cílem je, aby hlavní web se-vezmou.cz, průvodce tvorbou svatebního webu, administrativní rozhraní a nabízené šablony odpovídaly v maximální rozumné míře zásadám **WCAG 2.2 na úrovni AA**.

Toto vyjádření je cílem a průběžným závazkem ke zlepšování; nejde o tvrzení, že každý jednotlivý prvek služby je za všech okolností plně v souladu se všemi kritérii WCAG 2.2 AA.

## Jak přístupnost ověřujeme

Přístupnost průběžně kontrolujeme zejména těmito způsoby:

- automatizovanými kontrolami vybraných šablon a barevných kombinací,
- kontrolou ovladatelnosti pomocí klávesnice a viditelnosti zaměření prvků,
- kontrolou barevného kontrastu a čitelnosti textu,
- kontrolou chování rozhraní při zvětšení textu a na menších displejích,
- respektováním systémového nastavení pro omezení animací (\`prefers-reduced-motion\`),
- průběžnými manuálními kontrolami s ohledem na použití asistivních technologií.

## Známá omezení

V současnosti víme zejména o těchto omezeních:

1. **PDF dokumenty ke stažení**  
   Některé tiskové dokumenty generované službou, například jmenovky nebo svatební oznámení, nemusí být opatřeny úplnou strukturou a tagy pro čtečky obrazovky. Informace podstatné pro používání služby se snažíme současně poskytovat také v textové podobě na webu.

2. **Mapy**  
   Mapové zobrazení může využívat obrazové nebo mapové dlaždice, které nejsou samy o sobě plně přístupné. Adresu místa proto zobrazujeme také v textové podobě a umožňujeme přejít do externí navigační služby.

3. **Obsah vložený uživateli**  
   Svatební weby obsahují texty, fotografie, odkazy a další obsah vložený samotnými uživateli. Rozhraní se snaží uživatele vést k přístupnému zadávání obsahu, nemůžeme však zaručit přístupnost každého uživatelského obsahu ani externích webů, na které uživatelé odkazují.

## Zpětná vazba a kontakt

Pokud na hlavním webu se-vezmou.cz nebo na svatebním webu vytvořeném prostřednictvím služby narazíte na problém s přístupností, napište nám na:

**info@se-vezmou.cz**

Do zprávy prosím pokud možno uveďte adresu stránky a stručný popis problému. Na podněty týkající se přístupnosti se snažíme reagovat nejpozději do **5 pracovních dnů**.`,
  en: `The **se-vezmou.cz** service aims to make its websites and user interface accessible to the widest possible audience, including people with disabilities or other accessibility needs.

The service is currently operated by a micro-enterprise within the meaning of Czech Act No. 424/2023 Coll., on accessibility requirements for certain products and services. Services provided by micro-enterprises are outside the obligations imposed by that Act. We therefore publish this statement voluntarily as an expression of our approach to accessibility.

## Accessibility status

Our goal is for the se-vezmou.cz website, the wedding website creation flow, the administration interface and the available templates to follow the **WCAG 2.2 Level AA** principles to the greatest reasonable extent.

This statement describes our target and ongoing commitment to improvement; it is not a representation that every individual part of the service fully satisfies every WCAG 2.2 AA success criterion in all circumstances.

## How we review accessibility

We review accessibility on an ongoing basis, in particular through:

- automated checks of selected templates and colour combinations,
- keyboard navigation and visible-focus checks,
- colour contrast and text readability checks,
- checks of the interface at increased zoom levels and on smaller screens,
- support for the system-level \`prefers-reduced-motion\` preference,
- ongoing manual checks with assistive-technology use in mind.

## Known limitations

We are currently aware of the following main limitations:

1. **Downloadable PDF documents**  
   Some printable documents generated by the service, such as name cards or wedding invitations, may not contain a complete tag structure for screen readers. Information necessary for using the service is also intended to be available in text form on the website.

2. **Maps**  
   Map displays may use image or map tiles that are not fully accessible on their own. Venue addresses are therefore also provided as text, together with links to external navigation services.

3. **User-generated content**  
   Wedding websites contain texts, photographs, links and other content uploaded by users. Our interface seeks to encourage accessible content creation, but we cannot guarantee the accessibility of all user-generated content or third-party websites linked by users.

## Feedback and contact

If you encounter an accessibility issue on se-vezmou.cz or on a wedding website created through the service, please contact us at:

**info@se-vezmou.cz**

Where possible, please include the page address and a short description of the issue. We aim to respond to accessibility feedback within **5 business days**.`,
};
